# In Class Notebook, Week 05

You can click on the GitHub URL of this notebook to access the file in near-real time: https://github.com/UIUC-iSchool-DataViz/is445_bcubcg_fall2023/blob/master/week05/inClass_week05.ipynb 

Or you can copy-paste into the nbviewer interface for a plain-text rendering:

https://kokes.github.io/nbviewer.js/viewer.html

In [1]:
import ipywidgets

In [2]:
islider = ipywidgets.IntSlider(min=0,max=10, step=1, orientation='vertical')
islider

IntSlider(value=0, max=10, orientation='vertical')

In [3]:
cp = ipywidgets.ColorPicker()
cp

ColorPicker(value='black')

In [4]:
ipywidgets.link( (cp,'value'), (islider.style, 'handle_color'))

In [5]:
class MyObject():
    name = 'unnamed'
    age = 0

In [6]:
my_obj = MyObject()

In [7]:
my_obj.name, my_obj.age

('unnamed', 0)

In [8]:
my_obj.name = 'Bob'
my_obj.age = 47

In [9]:
print('Hello, my name is', my_obj.name, 'and I am', my_obj.age, 'years old')

Hello, my name is Bob and I am 47 years old


In [10]:
my_obj.name = 'Linda'
my_obj.age = 45

In [11]:
print('Hello, my name is', my_obj.name, 'and I am', my_obj.age, 'years old')

Hello, my name is Linda and I am 45 years old


In [12]:
import traitlets

In [13]:
# class MyObject():
#     name = 'unnamed'
#     age = 0

class MyTraitletObject(traitlets.HasTraits):
    name = traitlets.Unicode('unnamed') # fancy of saying formatting string
    age = traitlets.Int(0) # similar to age = 0, but fancy

In [14]:
my_t_obj = MyTraitletObject()
my_t_obj.name = 'Bob'
my_t_obj.age = 47

In [15]:
my_t_obj.name, my_t_obj.age

('Bob', 47)

In [16]:
print('Hello, my name is', my_t_obj.name, 'and I am', my_t_obj.age, 'years old')

Hello, my name is Bob and I am 47 years old


In [17]:
def name_changed(change):
    print(change)
    
my_t_obj.observe(name_changed, ['name'])

In [18]:
my_t_obj.name = 'Linda'

{'name': 'name', 'old': 'Bob', 'new': 'Linda', 'owner': <__main__.MyTraitletObject object at 0x7fe7f80deb20>, 'type': 'change'}


In [19]:
def name_changed2(change):
    print('Hello, my name is', change['new'], 'and I am', 
          change['owner'].age, 'years old')
    
my_t_obj.observe(name_changed2, ['name'])

In [20]:
my_t_obj.name = 'Bob'

{'name': 'name', 'old': 'Linda', 'new': 'Bob', 'owner': <__main__.MyTraitletObject object at 0x7fe7f80deb20>, 'type': 'change'}
Hello, my name is Bob and I am 47 years old


In [21]:
my_t_obj.unobserve(name_changed, ['name'])

In [22]:
my_t_obj.name = 'Linda'

Hello, my name is Linda and I am 47 years old


In [23]:
def age_changed(change):
    print('Hello, my name is', change['owner'].name, 'and I am', 
         change['new'], 'years old')
my_t_obj.observe(age_changed, ['age'])

In [24]:
my_t_obj.age = 45

Hello, my name is Linda and I am 45 years old


In [25]:
my_t_obj.name, my_t_age = 'Louise', 8

Hello, my name is Louise and I am 45 years old


## Onto bqplot!

In [1]:
import bqplot
import numpy as np

**Step 1: Data**

In [27]:
x = np.arange(100)

In [28]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [29]:
y = np.random.random(100)

In [30]:
y

array([1.62381502e-01, 8.97002548e-01, 2.32082665e-01, 3.27385341e-01,
       9.68703600e-01, 7.39343437e-01, 8.71832811e-01, 4.75900007e-01,
       8.60471850e-01, 4.13857104e-01, 5.02701892e-01, 1.78266706e-01,
       1.36666780e-01, 3.68426910e-01, 7.52099702e-01, 4.60926320e-01,
       8.94230925e-01, 4.45056535e-01, 3.37995064e-01, 2.70542989e-01,
       2.71781363e-01, 8.47604982e-01, 5.99005770e-01, 5.19918242e-01,
       2.55207527e-01, 6.83709803e-01, 7.90210712e-01, 8.32889680e-01,
       4.49724777e-02, 4.68057151e-01, 8.88741971e-01, 5.23616689e-01,
       8.62514296e-01, 1.14652301e-01, 8.48313912e-01, 7.10712158e-01,
       8.65235264e-01, 2.09059134e-01, 4.19479230e-01, 7.35474041e-02,
       3.37295409e-01, 3.99625648e-01, 4.65996295e-01, 1.94888287e-01,
       6.18194222e-01, 6.99414556e-01, 3.51456830e-01, 6.21899385e-02,
       4.96684901e-01, 8.19784357e-01, 3.15276332e-01, 2.85879136e-01,
       8.90344097e-01, 2.70922121e-01, 1.58971922e-01, 6.21419696e-01,
      

**Step 2: Scales**

In [31]:
bqplot.LinearScale?

In [32]:
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

**Step 3: Marks**

In [33]:
bqplot.Lines?

In [34]:
lines = bqplot.Lines(x=x, y=y,
                    scales={'x':x_sc, 'y':y_sc})

**Step 4 (though sometimes this is step 3!): Axis**

In [35]:
bqplot.Axis?

In [36]:
ax_x = bqplot.Axis(scale=x_sc, label='X Value')
ax_y = bqplot.Axis(scale=y_sc, label='Y Value', orientation='vertical')

**Step 5: Figure (here-ish is where any interactivity would be)**

In [37]:
bqplot.Figure?

In [38]:
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y])
fig

In [39]:
bqplot.interacts?

In [40]:
bqplot.interacts.PanZoom?

In [41]:
pz = bqplot.interacts.PanZoom(scales={'x':[x_sc], 'y':[y_sc]})

In [42]:
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y], interaction = pz)
fig

### Scatter plot with random data and point selection (brush selection)

In [2]:
# 1. Data
x = np.random.random(100)
y = np.random.random(100)

In [6]:
# 2. scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

In [7]:
# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='X')
y_ax = bqplot.Axis(scale=y_sc, label = 'Y', orientation='vertical')

In [8]:
bqplot.Scatter?

In [9]:
# 4. marks (Scatter)
scatters = bqplot.Scatter(x=x, y=y, scales={'x':x_sc, 'y':y_sc})

In [11]:
# ESC+a for insert above
bqplot.interacts.FastIntervalSelector?

In [12]:
# 5. interaction
selector = bqplot.interacts.FastIntervalSelector(scale=x_sc, marks = [scatters])

In [14]:
fig = bqplot.Figure(marks=[scatters], axes=[x_ax, y_ax], interaction=selector)
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

In [16]:
selector.selected

array([-0.0005307 ,  0.20030176])

In [18]:
scatters.unselected_style = {'opacity':0.8} # unselected, a little see-through
scatters.selected_style = {'fill':'red', 'stroke':'yellow'}

## Heatmap in 2D

In [2]:
import bqplot
import numpy as np

In [14]:
# 1. Data
data = np.random.random((10,10))

In [22]:
bqplot.ColorScale?

In [23]:
# 2. Scales (just with color scale)
col_sc = bqplot.ColorScale()

# 3. Axis (skip)

# 4. Mark
heat_map = bqplot.GridHeatMap(color=data, scales = {'color':col_sc})

# 5. interactivity (skip)

# 6. finally, a figure
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.70038…

In [24]:
bqplot.GridHeatMap?

In [25]:
# 2. Scales (just with color scale)
col_sc = bqplot.ColorScale(scheme='Blues')

# 3. Axis (skip)

# 4. Mark
heat_map = bqplot.GridHeatMap(color=data, scales = {'color':col_sc})

# 5. interactivity (skip)

# 6. finally, a figure
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.70038…

In [26]:
bqplot.ColorAxis?

In [27]:
# 2. Scales (just with color scale)
col_sc = bqplot.ColorScale(scheme='Blues')

# 3. Axis 
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. Mark
heat_map = bqplot.GridHeatMap(color=data, scales = {'color':col_sc})

# 5. interactivity (skip)

# 6. finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Blues'), side='right')], fig_margin={'…

No such comm: 526e3cad15804663852974ee8884db82
No such comm: 526e3cad15804663852974ee8884db82
No such comm: 526e3cad15804663852974ee8884db82
No such comm: 526e3cad15804663852974ee8884db82
No such comm: 526e3cad15804663852974ee8884db82


In [28]:
# 2. Scales 
col_sc = bqplot.ColorScale(scheme='Blues')
x_sc = bqplot.OrdinalScale() # ordered bin numbers
y_sc = bqplot.OrdinalScale()

# 3. Axis 
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')

# 4. Mark
heat_map = bqplot.GridHeatMap(color=data, scales = {'color':col_sc})

# 5. interactivity (skip)

# 6. finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Blues'), side='right'), Axis(label='Co…

No such comm: 7049e38645ee490f8ec67e1554fb6c18
No such comm: 7049e38645ee490f8ec67e1554fb6c18


In [4]:
# 2. Scales 
col_sc = bqplot.ColorScale(scheme='Blues')
x_sc = bqplot.OrdinalScale() # ordered bin numbers
y_sc = bqplot.OrdinalScale()

# 3. Axis 
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')

# 4. Mark
heat_map = bqplot.GridHeatMap(color=data, scales = {'color':col_sc,
                                                   'row':y_sc,
                                                   'column':x_sc},
                             interactions = {'click':'select'},
                             anchor_style={'fill':'red'})

# 5. interactivity (skip)

# 6. finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Blues'), side='right'), Axis(label='Co…

In [5]:
heat_map.selected

array([[3, 3]])

In [7]:
import ipywidgets

In [8]:
myLabel = ipywidgets.Label()

In [9]:
myLabel

Label(value='')

In [10]:
myLabel.value = 'Data value = '

In [11]:
# 2. Scales 
col_sc = bqplot.ColorScale(scheme='Blues')
x_sc = bqplot.OrdinalScale() # ordered bin numbers
y_sc = bqplot.OrdinalScale()

# 3. Axis 
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')

# 4. Mark
heat_map = bqplot.GridHeatMap(color=data, scales = {'color':col_sc,
                                                   'row':y_sc,
                                                   'column':x_sc},
                             interactions = {'click':'select'},
                             anchor_style={'fill':'red'})

# 5. interactivity 
def on_selected(change):
    print(change)
heat_map.observe(on_selected, 'selected')

# 6. finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Blues'), side='right'), Axis(label='Co…

{'name': 'selected', 'old': None, 'new': array([[0, 0]]), 'owner': GridHeatMap(anchor_style={'fill': 'red'}, color=array([[0.53468473, 0.58402246, 0.5651327 , 0.5514027 , 0.22311885,
        0.13820927, 0.73654254, 0.38911282, 0.42160082, 0.83348024],
       [0.721861  , 0.0036693 , 0.12471514, 0.56887637, 0.4627813 ,
        0.53012346, 0.47584434, 0.09921991, 0.9454382 , 0.94667641],
       [0.38659402, 0.28687299, 0.33524561, 0.8017765 , 0.90320668,
        0.95950303, 0.05798183, 0.33286445, 0.51746625, 0.25081624],
       [0.39391042, 0.10180096, 0.00845126, 0.43906519, 0.52637264,
        0.76662125, 0.13649299, 0.09557948, 0.004432  , 0.42144636],
       [0.37613444, 0.54121825, 0.84828261, 0.43389516, 0.23772923,
        0.70993606, 0.01920117, 0.91925003, 0.02290521, 0.14332296],
       [0.09521091, 0.26294591, 0.27664038, 0.1239107 , 0.45969907,
        0.26569041, 0.06243017, 0.40111869, 0.75768595, 0.27955514],
       [0.65748675, 0.60025598, 0.94562134, 0.15217116, 0.75206

In [12]:
# 2. Scales 
col_sc = bqplot.ColorScale(scheme='Blues')
x_sc = bqplot.OrdinalScale() # ordered bin numbers
y_sc = bqplot.OrdinalScale()

# 3. Axis 
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')

# 4. Mark
heat_map = bqplot.GridHeatMap(color=data, scales = {'color':col_sc,
                                                   'row':y_sc,
                                                   'column':x_sc},
                             interactions = {'click':'select'},
                             anchor_style={'fill':'red'})

# 5. interactivity 
def on_selected(change):
    #print(change)
    print(change['owner'].selected)
heat_map.observe(on_selected, 'selected')

# 6. finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Blues'), side='right'), Axis(label='Co…

[[4 2]]
[[4 3]]
[[4 4]]
[[3 4]]
[[4 4]
 [3 4]]
[[4 5]
 [3 4]
 [3 5]
 [4 4]]


In [15]:
# 2. Scales 
col_sc = bqplot.ColorScale(scheme='Blues')
x_sc = bqplot.OrdinalScale() # ordered bin numbers
y_sc = bqplot.OrdinalScale()

# 3. Axis 
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')

# 4. Mark
heat_map = bqplot.GridHeatMap(color=data, scales = {'color':col_sc,
                                                   'row':y_sc,
                                                   'column':x_sc},
                             interactions = {'click':'select'},
                             anchor_style={'fill':'red'})

# 5. interactivity 
def on_selected(change):
    #print(change)
    if len(change['owner'].selected) == 1:
        print(change['owner'].selected[0])
heat_map.observe(on_selected, 'selected')

# 6. finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Blues'), side='right'), Axis(label='Co…

[3 2]
[3 3]
[1 3]
[1 2]
[2 2]


In [17]:
myLabel.value

'Data value = '

In [18]:
# 2. Scales 
col_sc = bqplot.ColorScale(scheme='Blues')
x_sc = bqplot.OrdinalScale() # ordered bin numbers
y_sc = bqplot.OrdinalScale()

# 3. Axis 
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')

# 4. Mark
heat_map = bqplot.GridHeatMap(color=data, scales = {'color':col_sc,
                                                   'row':y_sc,
                                                   'column':x_sc},
                             interactions = {'click':'select'},
                             anchor_style={'fill':'red'})

# 5. interactivity 
def on_selected(change):
    #print(change)
    if len(change['owner'].selected) == 1:
        #print(change['owner'].selected[0])
        i,j = change['owner'].selected[0]
        myLabel.value = 'Data value = ' + str(data[i,j])
heat_map.observe(on_selected, 'selected')

# 6. finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Blues'), side='right'), Axis(label='Co…

In [19]:
myLabel

Label(value='Data value = 0.9966194164908724')

In [20]:
# 2. Scales 
col_sc = bqplot.ColorScale(scheme='Blues')
x_sc = bqplot.OrdinalScale() # ordered bin numbers
y_sc = bqplot.OrdinalScale()

# 3. Axis 
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')

# 4. Mark
heat_map = bqplot.GridHeatMap(color=data, scales = {'color':col_sc,
                                                   'row':y_sc,
                                                   'column':x_sc},
                             interactions = {'click':'select'},
                             anchor_style={'fill':'red'})

# 5. interactivity 
def on_selected(change):
    #print(change)
    if len(change['owner'].selected) == 1:
        i,j = change['owner'].selected[0]
        myLabel.value = 'Data value = ' + str(data[i,j])
heat_map.observe(on_selected, 'selected')

# 6. finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
#fig

dashboard = ipywidgets.VBox([myLabel, fig])

In [21]:
dashboard

## 3d Random data

In [22]:
data3d = np.random.random((10,10,20))

In [23]:
data3d.shape

(10, 10, 20)

In [25]:
data3d[0,0,:]

array([0.761059  , 0.8955471 , 0.23863323, 0.91923834, 0.19040461,
       0.68734487, 0.66115963, 0.69535971, 0.92636613, 0.38461568,
       0.38892705, 0.77158782, 0.33287259, 0.43470371, 0.81382018,
       0.83800225, 0.33954044, 0.45004561, 0.180503  , 0.80008809])

In [29]:
np.sum(data3d,axis=2).shape

(10, 10)

In [32]:
# 2. Scales 
col_sc = bqplot.ColorScale(scheme='Blues')
x_sc = bqplot.OrdinalScale() # ordered bin numbers
y_sc = bqplot.OrdinalScale()

# 3. Axis 
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')

# 4. Mark
heat_map = bqplot.GridHeatMap(color=np.sum(data3d,axis=2), 
                              scales = {'color':col_sc,
                                                   'row':y_sc,
                                                   'column':x_sc},
                             interactions = {'click':'select'},
                             anchor_style={'fill':'red'})

# 5. interactivity 
def on_selected(change):
    #print(change)
    if len(change['owner'].selected) == 1:
        i,j = change['owner'].selected[0]
        myLabel.value = 'Data value = ' + str(np.sum(data3d[i,j,:]))
heat_map.observe(on_selected, 'selected')

# 6. finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
#fig

dashboard = ipywidgets.VBox([myLabel, fig])
dashboard

In [33]:
i,j = 3,5

In [34]:
data3d[i,j]

array([0.48013822, 0.92614192, 0.28203368, 0.50912949, 0.5709601 ,
       0.42275298, 0.23365144, 0.52809607, 0.41532248, 0.30046323,
       0.64359927, 0.87166884, 0.86887681, 0.1522757 , 0.70521569,
       0.70316364, 0.44025269, 0.47707822, 0.84079454, 0.46179679])